name: pdf
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install texlive
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
      - name: build
        run: |
          cd tex
          pdflatex -interaction=nonstopmode -halt-on-error main.tex
      - uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: tex/main.pdf
